package com.visitorapp.util;


public final class RandomData {
	
	public static final String[] NAMES = new String[] {
		"Tonda Lindley",
		"Stormy Holly",
		"Lizette Rivas",
		"Marna Costa",
		"Tressie Wingfield",
		"Charley Carman",
		"Herschel Held",
		"Winnifred Spann",
		"Katharine Gooden",
		"Sydney Fife",
		"Nelly Gunther",
		"Candy Cooke",
		"Mauricio Dang",
		"Robt Gough",
		"Johana Messer",
		"Lisandra Thibodeau",
		"Miquel Minnick",
		"Loni Reinhart",
		"Lupe Groves",
		"Vanetta Gale",
		"Hank Vang",
		"Stasia Posey",
		"Laure Casper",
		"Kenya Curtin",
		"Emely Utley",
		"Erasmo Derr",
		"Matha Rodrigues",
		"Laraine Bowlin",
		"Lala Lafferty",
		"Marchelle Matheson",
		"Deloras Gainey",
		"Li Jude",
		"Weston Merrick",
		"Chana Ali",
		"Leda South",
		"Shandra Bachman",
		"Edwardo Sipes",
		"Mirella Bottoms",
		"Jennell Crocker",
		"Hee Swift",
		"Andra Zuniga",
		"Cecil Waldron",
		"Assunta Loyd",
		"John Noriega",
		"Angelita Cushman",
		"Estefana Archer",
		"Babara Puckett",
		"Marlyn Packer",
		"Collen Agnew",
		"Alexander Khan",
		"Chantay Shackelford",
		"Jonas Samson",
		"Kimberley Earley",
		"Rasheeda Bone",
		"Theresia Balderas",
		"Toya Robison",
		"Torri Frey",
		"Harris Couture",
		"Lorelei Ferrara",
		"Lavonia Goble",
		"Portia Morrow",
		"Terica Pulido",
		"Valarie Poulin",
		"Maia Paige",
		"Floria Goldstein",
		"Epifania Brink",
		"Shalon Fitch",
		"Sona Rowan",
		"Lyndon Coffin",
		"Delinda Pereira",
		"Hae Stjohn",
		"Hermelinda Easter",
		"Ghislaine Irish",
		"Annetta Guerra",
		"Janna Hartman",
		"Anjelica Scholl",
		"Lissette Haney",
		"Eladia Sales",
		"Jacquelyne Roldan",
		"Sung Helm",
		"Chadwick Dick",
		"Geralyn Varney",
		"Gracia Albers",
		"Galina Humphrey",
		"Albertha Finnegan",
		"Concetta Mcmullen",
		"Ayana Dougherty",
		"Bertie Daly",
		"Debroah Gregg",
		"Deadra Branch",
		"Danelle Aleman",
		"Flossie Zeller",
		"Betsey Hickman",
		"Rosario Novak",
		"Kelsi Lapointe",
		"Annis Tuck",
		"Piedad Dodd",
		"Cheyenne Grayson",
		"Kiyoko Fulcher",
		"Millard Halsey"
	};
	
	public final static String[] ADDRS = new String[] {
		"Coulobres, France",
		"Champagnier, France",
		"Gibret, France",
		"Ladinhac, France",
		"Breugny, France",
		"Niederhergheim, France",
		"Ance, France",
		"Mazzola, France",
		"Pierlas, France",
		"Ounans, France",
		"Yvoire, France",
		"Montrotier, France",
		"Acon, France",
		"Agny, France",
		"Meurger, France",
		"Monnetay, France",
		"Nieudan, France",
		"Island, France",
		"Noncourt, France",
		"Salgues, France",
		"Lastours, France",
		"Croutelle, France",
		"Kerlaeron, France",
		"Pers, France",
		"Valcourt, France",
		"Jacob, France",
		"Roumoules, France",
		"Cierrey, France",
		"Lamnay, France",
		"Aumage, France",
		"Andance, France",
		"Vacon, France",
		"Lesgoul, France",
		"Vico, France",
		"Verna, France",
		"Jarnages, France",
		"Sournac, France",
		"Bostbarty, France",
		"Concremiers, France",
		"Aymeries, France",
		"Capoulet, France",
		"Provence, France",
		"Thise, France",
		"Laval, France",
		"Durbans, France",
		"Landersheim, France",
		"Courreau, France",
		"Fresnois, France",
		"Bessans, France",
		"Villegondoux, France"
	};
	
	public static final String[] LOC_NAMES = new String[] {
		"Downtown",
		"Abydos",
		"Aegis",
		"Aldébaran-4",
		"Altair",
		"Amel",
		"Antar",
		"Athena",
		"Aurelia",
		"Avalon",
		"Belzagor",
		"Botany",
		"Bronson",
		"Chthon",
		"Cyteen",
		"Cybertron",
		"Darwin",
		"Deucalion",
		"Dosadi",
		"Downbelow",
		"Erna",
		"Erythro",
		"Eternia",
		"Etheria",
		"Fhloston",
		"Finisterre",
		"Fiorina"
	};
}
