package com.visitorapp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CustomerStoreVisit service. Represents a row in the &quot;VisitorApp_CustomerStoreVisit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.visitorapp.model.impl.CustomerStoreVisitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.visitorapp.model.impl.CustomerStoreVisitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerStoreVisit
 * @see com.visitorapp.model.impl.CustomerStoreVisitImpl
 * @see com.visitorapp.model.impl.CustomerStoreVisitModelImpl
 * @generated
 */
public interface CustomerStoreVisitModel extends BaseModel<CustomerStoreVisit>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a customer store visit model instance should use the {@link CustomerStoreVisit} interface instead.
     */

    /**
     * Returns the primary key of this customer store visit.
     *
     * @return the primary key of this customer store visit
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this customer store visit.
     *
     * @param primaryKey the primary key of this customer store visit
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the customerstorevisit ID of this customer store visit.
     *
     * @return the customerstorevisit ID of this customer store visit
     */
    public long getCustomerstorevisitId();

    /**
     * Sets the customerstorevisit ID of this customer store visit.
     *
     * @param customerstorevisitId the customerstorevisit ID of this customer store visit
     */
    public void setCustomerstorevisitId(long customerstorevisitId);

    /**
     * Returns the group ID of this customer store visit.
     *
     * @return the group ID of this customer store visit
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this customer store visit.
     *
     * @param groupId the group ID of this customer store visit
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this customer store visit.
     *
     * @return the company ID of this customer store visit
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this customer store visit.
     *
     * @param companyId the company ID of this customer store visit
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this customer store visit.
     *
     * @return the user ID of this customer store visit
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this customer store visit.
     *
     * @param userId the user ID of this customer store visit
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this customer store visit.
     *
     * @return the user uuid of this customer store visit
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this customer store visit.
     *
     * @param userUuid the user uuid of this customer store visit
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this customer store visit.
     *
     * @return the user name of this customer store visit
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this customer store visit.
     *
     * @param userName the user name of this customer store visit
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this customer store visit.
     *
     * @return the create date of this customer store visit
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this customer store visit.
     *
     * @param createDate the create date of this customer store visit
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this customer store visit.
     *
     * @return the modified date of this customer store visit
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this customer store visit.
     *
     * @param modifiedDate the modified date of this customer store visit
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the customer ID of this customer store visit.
     *
     * @return the customer ID of this customer store visit
     */
    public long getCustomerId();

    /**
     * Sets the customer ID of this customer store visit.
     *
     * @param customerId the customer ID of this customer store visit
     */
    public void setCustomerId(long customerId);

    /**
     * Returns the storelocation ID of this customer store visit.
     *
     * @return the storelocation ID of this customer store visit
     */
    public long getStorelocationId();

    /**
     * Sets the storelocation ID of this customer store visit.
     *
     * @param storelocationId the storelocation ID of this customer store visit
     */
    public void setStorelocationId(long storelocationId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(CustomerStoreVisit customerStoreVisit);

    @Override
    public int hashCode();

    @Override
    public CacheModel<CustomerStoreVisit> toCacheModel();

    @Override
    public CustomerStoreVisit toEscapedModel();

    @Override
    public CustomerStoreVisit toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
