package com.visitorapp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StoreLocation service. Represents a row in the &quot;VisitorApp_StoreLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.visitorapp.model.impl.StoreLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.visitorapp.model.impl.StoreLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreLocation
 * @see com.visitorapp.model.impl.StoreLocationImpl
 * @see com.visitorapp.model.impl.StoreLocationModelImpl
 * @generated
 */
public interface StoreLocationModel extends BaseModel<StoreLocation>,
    GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a store location model instance should use the {@link StoreLocation} interface instead.
     */

    /**
     * Returns the primary key of this store location.
     *
     * @return the primary key of this store location
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this store location.
     *
     * @param primaryKey the primary key of this store location
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the storelocation ID of this store location.
     *
     * @return the storelocation ID of this store location
     */
    public long getStorelocationId();

    /**
     * Sets the storelocation ID of this store location.
     *
     * @param storelocationId the storelocation ID of this store location
     */
    public void setStorelocationId(long storelocationId);

    /**
     * Returns the group ID of this store location.
     *
     * @return the group ID of this store location
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this store location.
     *
     * @param groupId the group ID of this store location
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this store location.
     *
     * @return the company ID of this store location
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this store location.
     *
     * @param companyId the company ID of this store location
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this store location.
     *
     * @return the user ID of this store location
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this store location.
     *
     * @param userId the user ID of this store location
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this store location.
     *
     * @return the user uuid of this store location
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this store location.
     *
     * @param userUuid the user uuid of this store location
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this store location.
     *
     * @return the user name of this store location
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this store location.
     *
     * @param userName the user name of this store location
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this store location.
     *
     * @return the create date of this store location
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this store location.
     *
     * @param createDate the create date of this store location
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this store location.
     *
     * @return the modified date of this store location
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this store location.
     *
     * @param modifiedDate the modified date of this store location
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this store location.
     *
     * @return the name of this store location
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this store location.
     *
     * @param name the name of this store location
     */
    public void setName(String name);

    /**
     * Returns the address of this store location.
     *
     * @return the address of this store location
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this store location.
     *
     * @param address the address of this store location
     */
    public void setAddress(String address);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(StoreLocation storeLocation);

    @Override
    public int hashCode();

    @Override
    public CacheModel<StoreLocation> toCacheModel();

    @Override
    public StoreLocation toEscapedModel();

    @Override
    public StoreLocation toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
