package com.visitorapp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.visitorapp.model.CustomerStoreVisit;

import com.visitorapp.service.CustomerStoreVisitLocalServiceUtil;

/**
 * The extended model base implementation for the CustomerStoreVisit service. Represents a row in the &quot;VisitorApp_CustomerStoreVisit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerStoreVisitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerStoreVisitImpl
 * @see com.visitorapp.model.CustomerStoreVisit
 * @generated
 */
public abstract class CustomerStoreVisitBaseImpl
    extends CustomerStoreVisitModelImpl implements CustomerStoreVisit {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a customer store visit model instance should use the {@link CustomerStoreVisit} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CustomerStoreVisitLocalServiceUtil.addCustomerStoreVisit(this);
        } else {
            CustomerStoreVisitLocalServiceUtil.updateCustomerStoreVisit(this);
        }
    }
}
