package com.visitorapp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.visitorapp.model.Customer;

import com.visitorapp.service.CustomerLocalServiceUtil;

/**
 * The extended model base implementation for the Customer service. Represents a row in the &quot;VisitorApp_Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomerImpl
 * @see com.visitorapp.model.Customer
 * @generated
 */
public abstract class CustomerBaseImpl extends CustomerModelImpl
    implements Customer {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a customer model instance should use the {@link Customer} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            CustomerLocalServiceUtil.addCustomer(this);
        } else {
            CustomerLocalServiceUtil.updateCustomer(this);
        }
    }
}
