package com.visitorapp.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.visitorapp.model.StoreLocation;
import com.visitorapp.model.StoreLocationModel;
import com.visitorapp.model.StoreLocationSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StoreLocation service. Represents a row in the &quot;VisitorApp_StoreLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.visitorapp.model.StoreLocationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StoreLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreLocationImpl
 * @see com.visitorapp.model.StoreLocation
 * @see com.visitorapp.model.StoreLocationModel
 * @generated
 */
@JSON(strict = true)
public class StoreLocationModelImpl extends BaseModelImpl<StoreLocation>
    implements StoreLocationModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a store location model instance should use the {@link com.visitorapp.model.StoreLocation} interface instead.
     */
    public static final String TABLE_NAME = "VisitorApp_StoreLocation";
    public static final Object[][] TABLE_COLUMNS = {
            { "storelocationId", Types.BIGINT },
            { "groupId", Types.BIGINT },
            { "companyId", Types.BIGINT },
            { "userId", Types.BIGINT },
            { "userName", Types.VARCHAR },
            { "createDate", Types.TIMESTAMP },
            { "modifiedDate", Types.TIMESTAMP },
            { "name", Types.VARCHAR },
            { "address", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table VisitorApp_StoreLocation (storelocationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,address VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table VisitorApp_StoreLocation";
    public static final String ORDER_BY_JPQL = " ORDER BY storeLocation.storelocationId ASC";
    public static final String ORDER_BY_SQL = " ORDER BY VisitorApp_StoreLocation.storelocationId ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.com.visitorapp.model.StoreLocation"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.com.visitorapp.model.StoreLocation"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = false;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.com.visitorapp.model.StoreLocation"));
    private static ClassLoader _classLoader = StoreLocation.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            StoreLocation.class
        };
    private long _storelocationId;
    private long _groupId;
    private long _companyId;
    private long _userId;
    private String _userUuid;
    private String _userName;
    private Date _createDate;
    private Date _modifiedDate;
    private String _name;
    private String _address;
    private StoreLocation _escapedModel;

    public StoreLocationModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static StoreLocation toModel(StoreLocationSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        StoreLocation model = new StoreLocationImpl();

        model.setStorelocationId(soapModel.getStorelocationId());
        model.setGroupId(soapModel.getGroupId());
        model.setCompanyId(soapModel.getCompanyId());
        model.setUserId(soapModel.getUserId());
        model.setUserName(soapModel.getUserName());
        model.setCreateDate(soapModel.getCreateDate());
        model.setModifiedDate(soapModel.getModifiedDate());
        model.setName(soapModel.getName());
        model.setAddress(soapModel.getAddress());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<StoreLocation> toModels(StoreLocationSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<StoreLocation> models = new ArrayList<StoreLocation>(soapModels.length);

        for (StoreLocationSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _storelocationId;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setStorelocationId(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _storelocationId;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return StoreLocation.class;
    }

    @Override
    public String getModelClassName() {
        return StoreLocation.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("storelocationId", getStorelocationId());
        attributes.put("groupId", getGroupId());
        attributes.put("companyId", getCompanyId());
        attributes.put("userId", getUserId());
        attributes.put("userName", getUserName());
        attributes.put("createDate", getCreateDate());
        attributes.put("modifiedDate", getModifiedDate());
        attributes.put("name", getName());
        attributes.put("address", getAddress());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        Long storelocationId = (Long) attributes.get("storelocationId");

        if (storelocationId != null) {
            setStorelocationId(storelocationId);
        }

        Long groupId = (Long) attributes.get("groupId");

        if (groupId != null) {
            setGroupId(groupId);
        }

        Long companyId = (Long) attributes.get("companyId");

        if (companyId != null) {
            setCompanyId(companyId);
        }

        Long userId = (Long) attributes.get("userId");

        if (userId != null) {
            setUserId(userId);
        }

        String userName = (String) attributes.get("userName");

        if (userName != null) {
            setUserName(userName);
        }

        Date createDate = (Date) attributes.get("createDate");

        if (createDate != null) {
            setCreateDate(createDate);
        }

        Date modifiedDate = (Date) attributes.get("modifiedDate");

        if (modifiedDate != null) {
            setModifiedDate(modifiedDate);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }

        String address = (String) attributes.get("address");

        if (address != null) {
            setAddress(address);
        }
    }

    @JSON
    @Override
    public long getStorelocationId() {
        return _storelocationId;
    }

    @Override
    public void setStorelocationId(long storelocationId) {
        _storelocationId = storelocationId;
    }

    @JSON
    @Override
    public long getGroupId() {
        return _groupId;
    }

    @Override
    public void setGroupId(long groupId) {
        _groupId = groupId;
    }

    @JSON
    @Override
    public long getCompanyId() {
        return _companyId;
    }

    @Override
    public void setCompanyId(long companyId) {
        _companyId = companyId;
    }

    @JSON
    @Override
    public long getUserId() {
        return _userId;
    }

    @Override
    public void setUserId(long userId) {
        _userId = userId;
    }

    @Override
    public String getUserUuid() throws SystemException {
        return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
    }

    @Override
    public void setUserUuid(String userUuid) {
        _userUuid = userUuid;
    }

    @JSON
    @Override
    public String getUserName() {
        if (_userName == null) {
            return StringPool.BLANK;
        } else {
            return _userName;
        }
    }

    @Override
    public void setUserName(String userName) {
        _userName = userName;
    }

    @JSON
    @Override
    public Date getCreateDate() {
        return _createDate;
    }

    @Override
    public void setCreateDate(Date createDate) {
        _createDate = createDate;
    }

    @JSON
    @Override
    public Date getModifiedDate() {
        return _modifiedDate;
    }

    @Override
    public void setModifiedDate(Date modifiedDate) {
        _modifiedDate = modifiedDate;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    @JSON
    @Override
    public String getAddress() {
        if (_address == null) {
            return StringPool.BLANK;
        } else {
            return _address;
        }
    }

    @Override
    public void setAddress(String address) {
        _address = address;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
            StoreLocation.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public StoreLocation toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (StoreLocation) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        StoreLocationImpl storeLocationImpl = new StoreLocationImpl();

        storeLocationImpl.setStorelocationId(getStorelocationId());
        storeLocationImpl.setGroupId(getGroupId());
        storeLocationImpl.setCompanyId(getCompanyId());
        storeLocationImpl.setUserId(getUserId());
        storeLocationImpl.setUserName(getUserName());
        storeLocationImpl.setCreateDate(getCreateDate());
        storeLocationImpl.setModifiedDate(getModifiedDate());
        storeLocationImpl.setName(getName());
        storeLocationImpl.setAddress(getAddress());

        storeLocationImpl.resetOriginalValues();

        return storeLocationImpl;
    }

    @Override
    public int compareTo(StoreLocation storeLocation) {
        long primaryKey = storeLocation.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof StoreLocation)) {
            return false;
        }

        StoreLocation storeLocation = (StoreLocation) obj;

        long primaryKey = storeLocation.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
    }

    @Override
    public CacheModel<StoreLocation> toCacheModel() {
        StoreLocationCacheModel storeLocationCacheModel = new StoreLocationCacheModel();

        storeLocationCacheModel.storelocationId = getStorelocationId();

        storeLocationCacheModel.groupId = getGroupId();

        storeLocationCacheModel.companyId = getCompanyId();

        storeLocationCacheModel.userId = getUserId();

        storeLocationCacheModel.userName = getUserName();

        String userName = storeLocationCacheModel.userName;

        if ((userName != null) && (userName.length() == 0)) {
            storeLocationCacheModel.userName = null;
        }

        Date createDate = getCreateDate();

        if (createDate != null) {
            storeLocationCacheModel.createDate = createDate.getTime();
        } else {
            storeLocationCacheModel.createDate = Long.MIN_VALUE;
        }

        Date modifiedDate = getModifiedDate();

        if (modifiedDate != null) {
            storeLocationCacheModel.modifiedDate = modifiedDate.getTime();
        } else {
            storeLocationCacheModel.modifiedDate = Long.MIN_VALUE;
        }

        storeLocationCacheModel.name = getName();

        String name = storeLocationCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            storeLocationCacheModel.name = null;
        }

        storeLocationCacheModel.address = getAddress();

        String address = storeLocationCacheModel.address;

        if ((address != null) && (address.length() == 0)) {
            storeLocationCacheModel.address = null;
        }

        return storeLocationCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(19);

        sb.append("{storelocationId=");
        sb.append(getStorelocationId());
        sb.append(", groupId=");
        sb.append(getGroupId());
        sb.append(", companyId=");
        sb.append(getCompanyId());
        sb.append(", userId=");
        sb.append(getUserId());
        sb.append(", userName=");
        sb.append(getUserName());
        sb.append(", createDate=");
        sb.append(getCreateDate());
        sb.append(", modifiedDate=");
        sb.append(getModifiedDate());
        sb.append(", name=");
        sb.append(getName());
        sb.append(", address=");
        sb.append(getAddress());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(31);

        sb.append("<model><model-name>");
        sb.append("com.visitorapp.model.StoreLocation");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>storelocationId</column-name><column-value><![CDATA[");
        sb.append(getStorelocationId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>groupId</column-name><column-value><![CDATA[");
        sb.append(getGroupId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>companyId</column-name><column-value><![CDATA[");
        sb.append(getCompanyId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userId</column-name><column-value><![CDATA[");
        sb.append(getUserId());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>userName</column-name><column-value><![CDATA[");
        sb.append(getUserName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>createDate</column-name><column-value><![CDATA[");
        sb.append(getCreateDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
        sb.append(getModifiedDate());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>address</column-name><column-value><![CDATA[");
        sb.append(getAddress());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
