package com.visitorapp.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.visitorapp.model.StoreLocation;

import com.visitorapp.service.StoreLocationLocalServiceUtil;

/**
 * The extended model base implementation for the StoreLocation service. Represents a row in the &quot;VisitorApp_StoreLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StoreLocationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StoreLocationImpl
 * @see com.visitorapp.model.StoreLocation
 * @generated
 */
public abstract class StoreLocationBaseImpl extends StoreLocationModelImpl
    implements StoreLocation {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a store location model instance should use the {@link StoreLocation} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StoreLocationLocalServiceUtil.addStoreLocation(this);
        } else {
            StoreLocationLocalServiceUtil.updateStoreLocation(this);
        }
    }
}
